version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5001/api
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5001"
    environment:
      - CORS_ALLOW_ORIGINS=http://localhost,https://localhost,http://nginx,https://nginx,https://bg-remover-2m1j.onrender.com
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge