version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5001/api
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Changed from 5000 to 5001
    environment:
      - CORS_ALLOW_ORIGINS=http://localhost:3000,http://frontend:3000
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/processed:/app/processed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

